# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hevos/Documents/CS4110/Vivado/LW2/Napelon/Napelon.srcs/sources_1/bd/cipher/ip/cipher_auto_pc_0/cipher_auto_pc_0.xci
# IP: The module: 'cipher_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hevos/Documents/CS4110/Vivado/LW2/Napelon/Napelon.gen/sources_1/bd/cipher/ip/cipher_auto_pc_0/cipher_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cipher_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/hevos/Documents/CS4110/Vivado/LW2/Napelon/Napelon.srcs/sources_1/bd/cipher/ip/cipher_auto_pc_0/cipher_auto_pc_0.xci
# IP: The module: 'cipher_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hevos/Documents/CS4110/Vivado/LW2/Napelon/Napelon.gen/sources_1/bd/cipher/ip/cipher_auto_pc_0/cipher_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cipher_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
