// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="radix_radix,hls_ip_2022_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.972000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=16415,HLS_SYN_LUT=14141,HLS_VERSION=2022_2}" *)

module radix (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 130'd1;
parameter    ap_ST_fsm_state2 = 130'd2;
parameter    ap_ST_fsm_state3 = 130'd4;
parameter    ap_ST_fsm_state4 = 130'd8;
parameter    ap_ST_fsm_state5 = 130'd16;
parameter    ap_ST_fsm_state6 = 130'd32;
parameter    ap_ST_fsm_state7 = 130'd64;
parameter    ap_ST_fsm_state8 = 130'd128;
parameter    ap_ST_fsm_state9 = 130'd256;
parameter    ap_ST_fsm_state10 = 130'd512;
parameter    ap_ST_fsm_state11 = 130'd1024;
parameter    ap_ST_fsm_state12 = 130'd2048;
parameter    ap_ST_fsm_state13 = 130'd4096;
parameter    ap_ST_fsm_state14 = 130'd8192;
parameter    ap_ST_fsm_state15 = 130'd16384;
parameter    ap_ST_fsm_state16 = 130'd32768;
parameter    ap_ST_fsm_state17 = 130'd65536;
parameter    ap_ST_fsm_state18 = 130'd131072;
parameter    ap_ST_fsm_state19 = 130'd262144;
parameter    ap_ST_fsm_state20 = 130'd524288;
parameter    ap_ST_fsm_state21 = 130'd1048576;
parameter    ap_ST_fsm_state22 = 130'd2097152;
parameter    ap_ST_fsm_state23 = 130'd4194304;
parameter    ap_ST_fsm_state24 = 130'd8388608;
parameter    ap_ST_fsm_state25 = 130'd16777216;
parameter    ap_ST_fsm_state26 = 130'd33554432;
parameter    ap_ST_fsm_state27 = 130'd67108864;
parameter    ap_ST_fsm_state28 = 130'd134217728;
parameter    ap_ST_fsm_state29 = 130'd268435456;
parameter    ap_ST_fsm_state30 = 130'd536870912;
parameter    ap_ST_fsm_state31 = 130'd1073741824;
parameter    ap_ST_fsm_state32 = 130'd2147483648;
parameter    ap_ST_fsm_state33 = 130'd4294967296;
parameter    ap_ST_fsm_state34 = 130'd8589934592;
parameter    ap_ST_fsm_state35 = 130'd17179869184;
parameter    ap_ST_fsm_state36 = 130'd34359738368;
parameter    ap_ST_fsm_state37 = 130'd68719476736;
parameter    ap_ST_fsm_state38 = 130'd137438953472;
parameter    ap_ST_fsm_state39 = 130'd274877906944;
parameter    ap_ST_fsm_state40 = 130'd549755813888;
parameter    ap_ST_fsm_state41 = 130'd1099511627776;
parameter    ap_ST_fsm_state42 = 130'd2199023255552;
parameter    ap_ST_fsm_state43 = 130'd4398046511104;
parameter    ap_ST_fsm_state44 = 130'd8796093022208;
parameter    ap_ST_fsm_state45 = 130'd17592186044416;
parameter    ap_ST_fsm_state46 = 130'd35184372088832;
parameter    ap_ST_fsm_state47 = 130'd70368744177664;
parameter    ap_ST_fsm_state48 = 130'd140737488355328;
parameter    ap_ST_fsm_state49 = 130'd281474976710656;
parameter    ap_ST_fsm_state50 = 130'd562949953421312;
parameter    ap_ST_fsm_state51 = 130'd1125899906842624;
parameter    ap_ST_fsm_state52 = 130'd2251799813685248;
parameter    ap_ST_fsm_state53 = 130'd4503599627370496;
parameter    ap_ST_fsm_state54 = 130'd9007199254740992;
parameter    ap_ST_fsm_state55 = 130'd18014398509481984;
parameter    ap_ST_fsm_state56 = 130'd36028797018963968;
parameter    ap_ST_fsm_state57 = 130'd72057594037927936;
parameter    ap_ST_fsm_state58 = 130'd144115188075855872;
parameter    ap_ST_fsm_state59 = 130'd288230376151711744;
parameter    ap_ST_fsm_state60 = 130'd576460752303423488;
parameter    ap_ST_fsm_state61 = 130'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 130'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 130'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 130'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 130'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 130'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 130'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 130'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 130'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 130'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 130'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 130'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 130'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 130'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 130'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 130'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 130'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 130'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 130'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 130'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 130'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 130'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 130'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 130'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 130'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 130'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 130'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 130'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 130'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 130'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 130'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 130'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 130'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 130'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 130'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 130'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 130'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 130'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 130'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 130'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 130'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 130'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 130'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 130'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 130'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 130'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 130'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 130'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 130'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 130'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 130'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 130'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 130'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 130'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 130'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 130'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 130'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 130'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 130'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 130'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 130'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 130'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 130'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 130'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 130'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 130'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 130'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 130'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 130'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 130'd680564733841876926926749214863536422912;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [129:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [7:0] input_r_q0;
wire   [2:0] output_r_address0;
reg    output_r_ce0;
reg    output_r_we0;
wire   [7:0] vla1_q1;
reg   [7:0] reg_220;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state45;
wire   [7:0] vla1_q0;
reg   [7:0] reg_224;
wire   [2:0] vla1_addr_reg_333;
wire    ap_CS_fsm_state3;
wire   [2:0] vla1_addr_1_reg_338;
wire   [2:0] vla1_addr_2_reg_343;
wire   [2:0] vla1_addr_3_reg_348;
reg   [7:0] vla1_load_2_reg_353;
wire    ap_CS_fsm_state5;
reg   [7:0] vla1_load_3_reg_358;
wire   [31:0] max_fu_233_p5;
reg   [31:0] max_reg_363;
wire    ap_CS_fsm_state6;
reg   [31:0] place_2_reg_376;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state44;
wire   [0:0] icmp_ln53_fu_255_p2;
wire    ap_CS_fsm_state46;
wire   [31:0] grp_fu_294_p2;
wire    ap_CS_fsm_state81;
wire   [4:0] trunc_ln18_fu_305_p1;
reg   [4:0] trunc_ln18_reg_402;
wire    ap_CS_fsm_state116;
wire   [31:0] count_q0;
reg   [31:0] count_load_reg_410;
wire    ap_CS_fsm_state123;
reg   [2:0] vla1_address0;
reg    vla1_ce0;
reg    vla1_we0;
reg   [7:0] vla1_d0;
reg   [2:0] vla1_address1;
reg    vla1_ce1;
reg    vla1_we1;
reg   [2:0] count_address0;
reg    count_ce0;
reg    count_we0;
reg   [31:0] count_d0;
reg    count_ce1;
wire   [31:0] count_q1;
reg   [3:0] output_address0;
reg    output_ce0;
reg    output_we0;
wire   [31:0] output_q0;
wire    grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_start;
wire    grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_done;
wire    grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_idle;
wire    grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_ready;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_input_r_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_input_r_ce0;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_ce0;
wire    grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_we0;
wire   [7:0] grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_d0;
wire    grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_start;
wire    grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_done;
wire    grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_idle;
wire    grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_ready;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_ce0;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_address1;
wire    grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_ce1;
wire   [31:0] grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_max_2_out;
wire    grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_max_2_out_ap_vld;
wire    grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_start;
wire    grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_done;
wire    grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_idle;
wire    grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_ready;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_ce0;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_address1;
wire    grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_ce1;
wire   [31:0] grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_max_5_out;
wire    grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_max_5_out_ap_vld;
wire    grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_start;
wire    grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_done;
wire    grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_idle;
wire    grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_ready;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_ce0;
wire    grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_we0;
wire   [31:0] grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_d0;
wire    grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_start;
wire    grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_done;
wire    grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_idle;
wire    grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_ready;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_ce0;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_address1;
wire    grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_ce1;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_ce0;
wire    grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_we0;
wire   [31:0] grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_d0;
wire    grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_start;
wire    grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_done;
wire    grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_idle;
wire    grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_ready;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_ce0;
wire    grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_we0;
wire   [31:0] grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_d0;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_address1;
wire    grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_ce1;
wire    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_start;
wire    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_done;
wire    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_idle;
wire    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_ready;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_ce0;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_address1;
wire    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_ce1;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_ce0;
wire    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_we0;
wire   [31:0] grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_d0;
wire   [3:0] grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_ce0;
wire    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_we0;
wire   [31:0] grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_d0;
wire    grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_start;
wire    grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_done;
wire    grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_idle;
wire    grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_ready;
wire   [3:0] grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_output_r_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_output_r_ce0;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_address0;
wire    grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_ce0;
wire    grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_we0;
wire   [7:0] grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_d0;
wire   [2:0] grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_address1;
wire    grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_ce1;
wire    grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_we1;
wire   [7:0] grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_d1;
reg    grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_start_reg;
wire    ap_CS_fsm_state117;
reg    grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_start_reg;
wire    ap_CS_fsm_state118;
wire    ap_CS_fsm_state119;
reg    grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_start_reg;
wire    ap_CS_fsm_state120;
wire    ap_CS_fsm_state121;
reg    grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_start_reg;
wire    ap_CS_fsm_state124;
wire    ap_CS_fsm_state125;
reg    grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_start_reg;
wire    ap_CS_fsm_state126;
wire    ap_CS_fsm_state127;
reg    grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_start_reg;
wire    ap_CS_fsm_state128;
wire    ap_CS_fsm_state129;
reg   [31:0] place_1_fu_72;
wire   [31:0] place_fu_271_p2;
wire    ap_CS_fsm_state130;
wire    ap_CS_fsm_state122;
wire   [31:0] grp_fu_250_p2;
wire   [31:0] shl_ln53_fu_261_p2;
wire   [31:0] shl_ln53_1_fu_266_p2;
wire   [31:0] grp_fu_294_p0;
wire   [4:0] grp_fu_299_p1;
wire   [4:0] grp_fu_299_p2;
reg    grp_fu_250_ap_start;
wire    grp_fu_250_ap_done;
reg    grp_fu_294_ap_start;
wire    grp_fu_294_ap_done;
reg    grp_fu_299_ap_start;
wire    grp_fu_299_ap_done;
reg   [129:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
wire    ap_ST_fsm_state91_blk;
wire    ap_ST_fsm_state92_blk;
wire    ap_ST_fsm_state93_blk;
wire    ap_ST_fsm_state94_blk;
wire    ap_ST_fsm_state95_blk;
wire    ap_ST_fsm_state96_blk;
wire    ap_ST_fsm_state97_blk;
wire    ap_ST_fsm_state98_blk;
wire    ap_ST_fsm_state99_blk;
wire    ap_ST_fsm_state100_blk;
wire    ap_ST_fsm_state101_blk;
wire    ap_ST_fsm_state102_blk;
wire    ap_ST_fsm_state103_blk;
wire    ap_ST_fsm_state104_blk;
wire    ap_ST_fsm_state105_blk;
wire    ap_ST_fsm_state106_blk;
wire    ap_ST_fsm_state107_blk;
wire    ap_ST_fsm_state108_blk;
wire    ap_ST_fsm_state109_blk;
wire    ap_ST_fsm_state110_blk;
wire    ap_ST_fsm_state111_blk;
wire    ap_ST_fsm_state112_blk;
wire    ap_ST_fsm_state113_blk;
wire    ap_ST_fsm_state114_blk;
wire    ap_ST_fsm_state115_blk;
wire    ap_ST_fsm_state116_blk;
reg    ap_ST_fsm_state117_blk;
wire    ap_ST_fsm_state118_blk;
reg    ap_ST_fsm_state119_blk;
wire    ap_ST_fsm_state120_blk;
reg    ap_ST_fsm_state121_blk;
wire    ap_ST_fsm_state122_blk;
wire    ap_ST_fsm_state123_blk;
wire    ap_ST_fsm_state124_blk;
reg    ap_ST_fsm_state125_blk;
wire    ap_ST_fsm_state126_blk;
reg    ap_ST_fsm_state127_blk;
wire    ap_ST_fsm_state128_blk;
reg    ap_ST_fsm_state129_blk;
wire    ap_ST_fsm_state130_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 130'd1;
#0 grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_start_reg = 1'b0;
#0 grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_start_reg = 1'b0;
#0 grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_start_reg = 1'b0;
#0 grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_start_reg = 1'b0;
#0 grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_start_reg = 1'b0;
#0 grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_start_reg = 1'b0;
#0 grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_start_reg = 1'b0;
#0 grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_start_reg = 1'b0;
end

radix_vla1_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
vla1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(vla1_address0),
    .ce0(vla1_ce0),
    .we0(vla1_we0),
    .d0(vla1_d0),
    .q0(vla1_q0),
    .address1(vla1_address1),
    .ce1(vla1_ce1),
    .we1(vla1_we1),
    .d1(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_d1),
    .q1(vla1_q1)
);

radix_count_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
count_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(count_address0),
    .ce0(count_ce0),
    .we0(count_we0),
    .d0(count_d0),
    .q0(count_q0),
    .address1(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_address1),
    .ce1(count_ce1),
    .q1(count_q1)
);

radix_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
output_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(output_address0),
    .ce0(output_ce0),
    .we0(output_we0),
    .d0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_d0),
    .q0(output_q0)
);

radix_radix_Pipeline_VITIS_LOOP_66_1 grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_start),
    .ap_done(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_done),
    .ap_idle(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_idle),
    .ap_ready(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_ready),
    .input_r_address0(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_input_r_address0),
    .input_r_ce0(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_input_r_ce0),
    .input_r_q0(input_r_q0),
    .vla1_address0(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_address0),
    .vla1_ce0(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_ce0),
    .vla1_we0(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_we0),
    .vla1_d0(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_d0)
);

radix_radix_Pipeline_VITIS_LOOP_9_1 grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_start),
    .ap_done(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_done),
    .ap_idle(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_idle),
    .ap_ready(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_ready),
    .max(max_reg_363),
    .vla1_address0(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_address0),
    .vla1_ce0(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_ce0),
    .vla1_q0(vla1_q0),
    .vla1_address1(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_address1),
    .vla1_ce1(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_ce1),
    .vla1_q1(vla1_q1),
    .max_2_out(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_max_2_out),
    .max_2_out_ap_vld(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_max_2_out_ap_vld)
);

radix_radix_Pipeline_VITIS_LOOP_20_1 grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_start),
    .ap_done(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_done),
    .ap_idle(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_idle),
    .ap_ready(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_ready),
    .max_4(trunc_ln18_reg_402),
    .vla1_address0(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_address0),
    .vla1_ce0(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_ce0),
    .vla1_q0(vla1_q0),
    .vla1_address1(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_address1),
    .vla1_ce1(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_ce1),
    .vla1_q1(vla1_q1),
    .place_1(place_2_reg_376),
    .max_5_out(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_max_5_out),
    .max_5_out_ap_vld(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_max_5_out_ap_vld)
);

radix_radix_Pipeline_VITIS_LOOP_26_2 grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_start),
    .ap_done(grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_done),
    .ap_idle(grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_idle),
    .ap_ready(grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_ready),
    .max_5_reload(grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_max_5_out),
    .count_address0(grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_address0),
    .count_ce0(grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_ce0),
    .count_we0(grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_we0),
    .count_d0(grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_d0)
);

radix_radix_Pipeline_VITIS_LOOP_30_3 grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_start),
    .ap_done(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_done),
    .ap_idle(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_idle),
    .ap_ready(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_ready),
    .vla1_address0(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_address0),
    .vla1_ce0(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_ce0),
    .vla1_q0(vla1_q0),
    .vla1_address1(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_address1),
    .vla1_ce1(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_ce1),
    .vla1_q1(vla1_q1),
    .place_1(place_2_reg_376),
    .count_address0(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_address0),
    .count_ce0(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_ce0),
    .count_we0(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_we0),
    .count_d0(grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_d0),
    .count_q0(count_q0)
);

radix_radix_Pipeline_VITIS_LOOP_34_4 grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_start),
    .ap_done(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_done),
    .ap_idle(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_idle),
    .ap_ready(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_ready),
    .count_load(count_load_reg_410),
    .count_address0(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_address0),
    .count_ce0(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_ce0),
    .count_we0(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_we0),
    .count_d0(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_d0),
    .count_address1(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_address1),
    .count_ce1(grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_ce1),
    .count_q1(count_q1)
);

radix_radix_Pipeline_VITIS_LOOP_38_5 grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_start),
    .ap_done(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_done),
    .ap_idle(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_idle),
    .ap_ready(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_ready),
    .vla1_address0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_address0),
    .vla1_ce0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_ce0),
    .vla1_q0(vla1_q0),
    .vla1_address1(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_address1),
    .vla1_ce1(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_ce1),
    .vla1_q1(vla1_q1),
    .place_1(place_2_reg_376),
    .count_address0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_address0),
    .count_ce0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_ce0),
    .count_we0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_we0),
    .count_d0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_d0),
    .count_q0(count_q0),
    .output_r_address0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_address0),
    .output_r_ce0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_ce0),
    .output_r_we0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_we0),
    .output_r_d0(grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_d0)
);

radix_radix_Pipeline_VITIS_LOOP_43_6 grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_start),
    .ap_done(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_done),
    .ap_idle(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_idle),
    .ap_ready(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_ready),
    .output_r_address0(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_output_r_address0),
    .output_r_ce0(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_output_r_ce0),
    .output_r_q0(output_q0),
    .vla1_address0(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_address0),
    .vla1_ce0(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_ce0),
    .vla1_we0(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_we0),
    .vla1_d0(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_d0),
    .vla1_address1(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_address1),
    .vla1_ce1(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_ce1),
    .vla1_we1(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_we1),
    .vla1_d1(grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_d1)
);

radix_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r_address0(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_input_r_address0),
    .input_r_ce0(grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_input_r_ce0),
    .input_r_q0(input_r_q0),
    .output_r_address0(output_r_address0),
    .output_r_ce0(output_r_ce0),
    .output_r_we0(output_r_we0),
    .output_r_d0(8'd0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

radix_sdiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_seq_1_U32(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_250_ap_start),
    .done(grp_fu_250_ap_done),
    .din0(grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_max_2_out),
    .din1(place_1_fu_72),
    .ce(1'b1),
    .dout(grp_fu_250_p2)
);

radix_sdiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_seq_1_U33(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_294_ap_start),
    .done(grp_fu_294_ap_done),
    .din0(grp_fu_294_p0),
    .din1(place_2_reg_376),
    .ce(1'b1),
    .dout(grp_fu_294_p2)
);

radix_srem_32ns_5ns_5_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 5 ))
srem_32ns_5ns_5_36_seq_1_U34(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_299_ap_start),
    .done(grp_fu_299_ap_done),
    .din0(grp_fu_294_p2),
    .din1(grp_fu_299_p1),
    .ce(1'b1),
    .dout(grp_fu_299_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state116)) begin
            grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_start_reg <= 1'b1;
        end else if ((grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_ready == 1'b1)) begin
            grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state118)) begin
            grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_start_reg <= 1'b1;
        end else if ((grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_ready == 1'b1)) begin
            grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state120)) begin
            grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_start_reg <= 1'b1;
        end else if ((grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_ready == 1'b1)) begin
            grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state124)) begin
            grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_ready == 1'b1)) begin
            grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state126)) begin
            grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_start_reg <= 1'b1;
        end else if ((grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_ready == 1'b1)) begin
            grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state128)) begin
            grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_start_reg <= 1'b1;
        end else if ((grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_ready == 1'b1)) begin
            grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_start_reg <= 1'b1;
        end else if ((grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_ready == 1'b1)) begin
            grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_start_reg <= 1'b1;
        end else if ((grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_ready == 1'b1)) begin
            grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        place_1_fu_72 <= 32'd1;
    end else if (((icmp_ln53_fu_255_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state44))) begin
        place_1_fu_72 <= place_fu_271_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state123)) begin
        count_load_reg_410 <= count_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        max_reg_363 <= max_fu_233_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        place_2_reg_376 <= place_1_fu_72;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_220 <= vla1_q1;
        reg_224 <= vla1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state116)) begin
        trunc_ln18_reg_402 <= trunc_ln18_fu_305_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        vla1_load_2_reg_353 <= vla1_q1;
        vla1_load_3_reg_358 <= vla1_q0;
    end
end

assign ap_ST_fsm_state100_blk = 1'b0;

assign ap_ST_fsm_state101_blk = 1'b0;

assign ap_ST_fsm_state102_blk = 1'b0;

assign ap_ST_fsm_state103_blk = 1'b0;

assign ap_ST_fsm_state104_blk = 1'b0;

assign ap_ST_fsm_state105_blk = 1'b0;

assign ap_ST_fsm_state106_blk = 1'b0;

assign ap_ST_fsm_state107_blk = 1'b0;

assign ap_ST_fsm_state108_blk = 1'b0;

assign ap_ST_fsm_state109_blk = 1'b0;

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state110_blk = 1'b0;

assign ap_ST_fsm_state111_blk = 1'b0;

assign ap_ST_fsm_state112_blk = 1'b0;

assign ap_ST_fsm_state113_blk = 1'b0;

assign ap_ST_fsm_state114_blk = 1'b0;

assign ap_ST_fsm_state115_blk = 1'b0;

assign ap_ST_fsm_state116_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_done == 1'b0)) begin
        ap_ST_fsm_state117_blk = 1'b1;
    end else begin
        ap_ST_fsm_state117_blk = 1'b0;
    end
end

assign ap_ST_fsm_state118_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_done == 1'b0)) begin
        ap_ST_fsm_state119_blk = 1'b1;
    end else begin
        ap_ST_fsm_state119_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state120_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_done == 1'b0)) begin
        ap_ST_fsm_state121_blk = 1'b1;
    end else begin
        ap_ST_fsm_state121_blk = 1'b0;
    end
end

assign ap_ST_fsm_state122_blk = 1'b0;

assign ap_ST_fsm_state123_blk = 1'b0;

assign ap_ST_fsm_state124_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_done == 1'b0)) begin
        ap_ST_fsm_state125_blk = 1'b1;
    end else begin
        ap_ST_fsm_state125_blk = 1'b0;
    end
end

assign ap_ST_fsm_state126_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_done == 1'b0)) begin
        ap_ST_fsm_state127_blk = 1'b1;
    end else begin
        ap_ST_fsm_state127_blk = 1'b0;
    end
end

assign ap_ST_fsm_state128_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_done == 1'b0)) begin
        ap_ST_fsm_state129_blk = 1'b1;
    end else begin
        ap_ST_fsm_state129_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state130_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

assign ap_ST_fsm_state91_blk = 1'b0;

assign ap_ST_fsm_state92_blk = 1'b0;

assign ap_ST_fsm_state93_blk = 1'b0;

assign ap_ST_fsm_state94_blk = 1'b0;

assign ap_ST_fsm_state95_blk = 1'b0;

assign ap_ST_fsm_state96_blk = 1'b0;

assign ap_ST_fsm_state97_blk = 1'b0;

assign ap_ST_fsm_state98_blk = 1'b0;

assign ap_ST_fsm_state99_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state130)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state130)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state122)) begin
        count_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        count_address0 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_address0;
    end else if ((1'b1 == ap_CS_fsm_state125)) begin
        count_address0 = grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_address0;
    end else if ((1'b1 == ap_CS_fsm_state121)) begin
        count_address0 = grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_address0;
    end else if ((1'b1 == ap_CS_fsm_state119)) begin
        count_address0 = grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_address0;
    end else begin
        count_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state122)) begin
        count_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        count_ce0 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_ce0;
    end else if ((1'b1 == ap_CS_fsm_state125)) begin
        count_ce0 = grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_ce0;
    end else if ((1'b1 == ap_CS_fsm_state121)) begin
        count_ce0 = grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_ce0;
    end else if ((1'b1 == ap_CS_fsm_state119)) begin
        count_ce0 = grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_ce0;
    end else begin
        count_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state125)) begin
        count_ce1 = grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_ce1;
    end else begin
        count_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state127)) begin
        count_d0 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_d0;
    end else if ((1'b1 == ap_CS_fsm_state125)) begin
        count_d0 = grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_d0;
    end else if ((1'b1 == ap_CS_fsm_state121)) begin
        count_d0 = grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_d0;
    end else if ((1'b1 == ap_CS_fsm_state119)) begin
        count_d0 = grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_d0;
    end else begin
        count_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state127)) begin
        count_we0 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_count_we0;
    end else if ((1'b1 == ap_CS_fsm_state125)) begin
        count_we0 = grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_count_we0;
    end else if ((1'b1 == ap_CS_fsm_state121)) begin
        count_we0 = grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_count_we0;
    end else if ((1'b1 == ap_CS_fsm_state119)) begin
        count_we0 = grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_count_we0;
    end else begin
        count_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_250_ap_start = 1'b1;
    end else begin
        grp_fu_250_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_294_ap_start = 1'b1;
    end else begin
        grp_fu_294_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state81)) begin
        grp_fu_299_ap_start = 1'b1;
    end else begin
        grp_fu_299_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        output_address0 = grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        output_address0 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_address0;
    end else begin
        output_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        output_ce0 = grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        output_ce0 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_ce0;
    end else begin
        output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state130) | (1'b1 == ap_CS_fsm_state44))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln53_fu_255_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state44))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state127)) begin
        output_we0 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_output_r_we0;
    end else begin
        output_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        vla1_address0 = vla1_addr_3_reg_348;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        vla1_address0 = vla1_addr_1_reg_338;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        vla1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        vla1_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state129)) begin
        vla1_address0 = grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_address0;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        vla1_address0 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_address0;
    end else if ((1'b1 == ap_CS_fsm_state121)) begin
        vla1_address0 = grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_address0;
    end else if ((1'b1 == ap_CS_fsm_state117)) begin
        vla1_address0 = grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        vla1_address0 = grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        vla1_address0 = grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_address0;
    end else begin
        vla1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        vla1_address1 = vla1_addr_2_reg_343;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        vla1_address1 = vla1_addr_reg_333;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        vla1_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        vla1_address1 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state129)) begin
        vla1_address1 = grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_address1;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        vla1_address1 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_address1;
    end else if ((1'b1 == ap_CS_fsm_state121)) begin
        vla1_address1 = grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_address1;
    end else if ((1'b1 == ap_CS_fsm_state117)) begin
        vla1_address1 = grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_address1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        vla1_address1 = grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_address1;
    end else begin
        vla1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state4))) begin
        vla1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state129)) begin
        vla1_ce0 = grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        vla1_ce0 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state121)) begin
        vla1_ce0 = grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state117)) begin
        vla1_ce0 = grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        vla1_ce0 = grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        vla1_ce0 = grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_ce0;
    end else begin
        vla1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state4))) begin
        vla1_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state129)) begin
        vla1_ce1 = grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state127)) begin
        vla1_ce1 = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_vla1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state121)) begin
        vla1_ce1 = grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_vla1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state117)) begin
        vla1_ce1 = grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_vla1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        vla1_ce1 = grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_vla1_ce1;
    end else begin
        vla1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        vla1_d0 = grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        vla1_d0 = grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_d0;
    end else begin
        vla1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        vla1_we0 = grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        vla1_we0 = grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_vla1_we0;
    end else begin
        vla1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        vla1_we1 = grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_vla1_we1;
    end else begin
        vla1_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            if (((icmp_ln53_fu_255_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state44))) begin
                ap_NS_fsm = ap_ST_fsm_state130;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            if (((grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state117))) begin
                ap_NS_fsm = ap_ST_fsm_state118;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state117;
            end
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            if (((grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state119))) begin
                ap_NS_fsm = ap_ST_fsm_state120;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state119;
            end
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            if (((grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state121))) begin
                ap_NS_fsm = ap_ST_fsm_state122;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state121;
            end
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            if (((grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state125))) begin
                ap_NS_fsm = ap_ST_fsm_state126;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state125;
            end
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            if (((grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state127))) begin
                ap_NS_fsm = ap_ST_fsm_state128;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state127;
            end
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            if (((grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state129))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state129;
            end
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state116 = ap_CS_fsm[32'd115];

assign ap_CS_fsm_state117 = ap_CS_fsm[32'd116];

assign ap_CS_fsm_state118 = ap_CS_fsm[32'd117];

assign ap_CS_fsm_state119 = ap_CS_fsm[32'd118];

assign ap_CS_fsm_state120 = ap_CS_fsm[32'd119];

assign ap_CS_fsm_state121 = ap_CS_fsm[32'd120];

assign ap_CS_fsm_state122 = ap_CS_fsm[32'd121];

assign ap_CS_fsm_state123 = ap_CS_fsm[32'd122];

assign ap_CS_fsm_state124 = ap_CS_fsm[32'd123];

assign ap_CS_fsm_state125 = ap_CS_fsm[32'd124];

assign ap_CS_fsm_state126 = ap_CS_fsm[32'd125];

assign ap_CS_fsm_state127 = ap_CS_fsm[32'd126];

assign ap_CS_fsm_state128 = ap_CS_fsm[32'd127];

assign ap_CS_fsm_state129 = ap_CS_fsm[32'd128];

assign ap_CS_fsm_state130 = ap_CS_fsm[32'd129];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state81 = ap_CS_fsm[32'd80];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_294_p0 = {{{{vla1_q0}, {vla1_q1}}, {reg_224}}, {reg_220}};

assign grp_fu_299_p1 = 32'd10;

assign grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_start = grp_radix_Pipeline_VITIS_LOOP_20_1_fu_179_ap_start_reg;

assign grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_start = grp_radix_Pipeline_VITIS_LOOP_26_2_fu_187_ap_start_reg;

assign grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_start = grp_radix_Pipeline_VITIS_LOOP_30_3_fu_193_ap_start_reg;

assign grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_start = grp_radix_Pipeline_VITIS_LOOP_34_4_fu_200_ap_start_reg;

assign grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_start = grp_radix_Pipeline_VITIS_LOOP_38_5_fu_206_ap_start_reg;

assign grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_start = grp_radix_Pipeline_VITIS_LOOP_43_6_fu_214_ap_start_reg;

assign grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_start = grp_radix_Pipeline_VITIS_LOOP_66_1_fu_164_ap_start_reg;

assign grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_start = grp_radix_Pipeline_VITIS_LOOP_9_1_fu_172_ap_start_reg;

assign icmp_ln53_fu_255_p2 = (($signed(grp_fu_250_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign max_fu_233_p5 = {{{{vla1_load_3_reg_358}, {vla1_load_2_reg_353}}, {reg_224}}, {reg_220}};

assign output_r_address0 = 64'd0;

assign place_fu_271_p2 = (shl_ln53_fu_261_p2 + shl_ln53_1_fu_266_p2);

assign shl_ln53_1_fu_266_p2 = place_1_fu_72 << 32'd1;

assign shl_ln53_fu_261_p2 = place_1_fu_72 << 32'd3;

assign trunc_ln18_fu_305_p1 = grp_fu_299_p2[4:0];

assign vla1_addr_1_reg_338 = 64'd1;

assign vla1_addr_2_reg_343 = 64'd2;

assign vla1_addr_3_reg_348 = 64'd3;

assign vla1_addr_reg_333 = 64'd0;

endmodule //radix
